/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiErrorHandler: typeof import('./src/components/common/ApiErrorHandler.vue')['default']
    AuthExample: typeof import('./src/components/AuthExample.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CategoryForm: typeof import('./src/components/Blog/CategoryForm.vue')['default']
    CategoryTable: typeof import('./src/components/Blog/CategoryTable.vue')['default']
    ErrorHandler: typeof import('./src/components/common/ErrorHandler.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PermissionList: typeof import('./src/components/Permission/PermissionList.vue')['default']
    PostCard: typeof import('./src/components/Blog/PostCard.vue')['default']
    PostForm: typeof import('./src/components/Blog/PostForm.vue')['default']
    PostTable: typeof import('./src/components/Blog/PostTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    SectionCard: typeof import('./src/components/Blog/SectionCard.vue')['default']
    SectionManager: typeof import('./src/components/Blog/SectionManager.vue')['default']
    SectionManagerNew: typeof import('./src/components/Blog/SectionManagerNew.vue')['default']
    TagInput: typeof import('./src/components/Blog/TagInput.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('./src/components/toast/Toast.vue')['default']
    ToastContainer: typeof import('./src/components/toast/ToastContainer.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    UserDeleteDialog: typeof import('./src/components/User/UserDeleteDialog.vue')['default']
    UserDetailCard: typeof import('./src/components/User/UserDetailCard.vue')['default']
    UserFilter: typeof import('./src/components/User/UserFilter.vue')['default']
    UserForm: typeof import('./src/components/User/UserForm.vue')['default']
    UserPermissionManager: typeof import('./src/components/Permission/UserPermissionManager.vue')['default']
    UserTable: typeof import('./src/components/User/UserTable.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
