[build]
  command = "npm run build"
  publish = "dist"

# API proxy pour éviter les erreurs CORS
[[redirects]]
  from = "/api/*"
  to = "https://lafaom-mao.vertex-cam.com/:splat"
  status = 200
  force = true

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"